FROM python:3.11-alpine

WORKDIR /app
ADD ./backend/requirements.txt /app/backend/

RUN pip install --upgrade pip
RUN pip install -r backend/requirements.txt

ADD ./docker /app/docker
ADD ./backend /app/backend