services:
  app:
    build:
      context: ./back
    ports: 
      - "8000:8000"
    volumes: 
      - ./back:/back
    command: 
      sh -c "python manage.py runserver 0.0.0.0:8000"
    environment:
      - DEBUG=1
