services:
  backend:
    build:
      context: ./back
    volumes:
      - static_data:/vol/web
    environment:
      - SECRET_KEY=samplesecret123
      - ALLOWED_HOSTS=127.0.0.1,localhost, 172.22.0.1, 10.0.0.212, 172.23.192.1
      - DEBUG=1
  frontend:
    build:
      context: ./front
    volumes:
      - react_build:/front/build
  proxy:
    build:
      context: ./proxy
    volumes:
      - static_data:/vol/static
      - react_build:/var/www/react
    ports:
      - "8080:8080"
    depends_on:
      - backend
      - frontend

volumes:
  static_data:
  react_build: