# Building Frontend
FROM node:lts-alpine as build

WORKDIR /app/frontend

COPY ./frontend/package.json ./
COPY ./frontend/package-lock.json ./

RUN npm ci --silent

COPY ./frontend/ ./

RUN npm run build

# Copy React static files and start nginx
FROM nginxinc/nginx-unprivileged:stable-alpine

COPY --from=build /app/frontend/build /usr/share/nginx/html

CMD ["nginx", "-g", "daemon off;"]